 export const tours = [
  {
    id: "1",
    title: "Everest Base Camp Trek",
    location: "Sagarmatha National Park, Nepal",
    rating: 4.9,
    difficulty: "Moderate to Challenging",
    days: 14,
    group: "8-12 people",
    altitude: "5,364m",
    seasons: "Sep-Nov, Mar-May",
    routes: [
      "Everest Base Camp – 12 Days",
      "Three Pass Trek – 21 Days",
      "Cho La Pass – 12/13 Days",
    ],
    highlights: [
      "Views of Mt. Everest",
      "Sherpa culture immersion",
      "Namche Bazaar visit",
      "Tengboche Monastery",
    ],
    image: "/destination/everest.jpeg",
    routeImage: "/routes/Everest.png",
    category: "Adventure",
  },
  {
    id: "2",
    title: "Annapurna Circuit Trek",
    location: "Annapurna Conservation Area, Nepal",
    rating: 4.8,
    difficulty: "Moderate",
    days: 16,
    group: "6-10 people",
    altitude: "5,416m",
    seasons: "Oct-Dec, Mar-May",
    routes: [
      "Annapurna Circuit – 16 Days",
      "Annapurna Base Camp – 12 Days",
      "Mardi Himal – 7 Days",
      "Ghorepani Poon Hill – 5 Days",
    ],
    highlights: [
      "Thorong La Pass crossing",
      "Diverse landscapes",
      "Hot springs at Jhinu",
      "Muktinath Temple",
    ],
    image: "/destination/anapurna.jpeg",
    routeImage: "/routes/Annapurna.png",
    category: "Adventure",
  },
  {
    title: "Langtang Valley Trek",
    location: "Langtang National Park, Nepal",
    rating: 4.7,
    difficulty: "Moderate",
    days: 10,
    group: "4-8 people",
    altitude: "4,984m",
    seasons: "Sep-Nov, Mar-May",
    routes: ["Langtang Valley Trek – 10 Days", "Helambu Trek – 7 Days"],
    highlights: [
      "Tamang heritage sites",
      "Kyanjin Gompa monastery",
      "Glacier views",
      "Wildlife spotting",
    ],
    image: "/destination/lantang.jpeg",
    routeImage: "/routes/Langatang.png",
    category: "Adventure",
  },
  {
    title: "Mardi Himal Trek",
    location: "Annapurna Region, Nepal",
    rating: 4.6,
    difficulty: "Moderate",
    days: 7,
    group: "4-10 people",
    altitude: "4,500m",
    seasons: "Sep-Nov, Mar-May",
    routes: ["Mardi Himal Trek – 7 Days"],
    highlights: [
      "Close-up views of Machhapuchhre",
      "Quiet off-the-beaten-path route",
      "Rhododendron forests",
      "Scenic ridge trails",
    ],
    image: "/destination/manaslu.jpeg",
    routeImage: "/routes/mardi.jpg",
    category: "Trek",
  },
  {
    title: "Ghorepani Poon Hill Trek",
    location: "Annapurna Region, Nepal",
    rating: 4.6,
    difficulty: "Easy to Moderate",
    days: 5,
    group: "4-12 people",
    altitude: "3,210m",
    seasons: "Sep-Nov, Mar-May",
    routes: ["Poon Hill Trek – 5 Days"],
    highlights: [
      "Sunrise over Annapurna & Dhaulagiri",
      "Short and scenic trek",
      "Gurung villages",
      "Rhododendron forests",
    ],
    image: "/destination/poonhill.jpeg",
    routeImage: "/routes/ghorepani.jpg",
    category: "Trek",
  },
  {
    title: "Manaslu Circuit Trek",
    location: "Manaslu Conservation Area, Nepal",
    rating: 4.8,
    difficulty: "Challenging",
    days: 15,
    group: "6-10 people",
    altitude: "5,160m",
    seasons: "Sep-Nov, Mar-May",
    routes: [
      "Manaslu Circuit – 14 Days",
      "Tsum Valley Trek – 18 Days",
      "Aka manasalu circuit trek",
    ],
    highlights: [
      "Larke La Pass crossing",
      "Remote cultural villages",
      "Manaslu base camp views",
      "Less crowded than Annapurna/Everest",
    ],
    image: "/destination/manaslum.jpeg",
    routeImage: "/routes/manaslu.png",
    category: "Adventure",
  },

  {
    title: "Dolpo Trek",
    location: "Shey Phoksundo, Dolpo, Nepal",
    rating: 4.7,
    difficulty: "Challenging",
    days: 18,
    group: "4-8 people",
    altitude: "5,151m",
    seasons: "May-Sep",
    routes: ["Upper Dolpo – 24 Days", "Lower Dolpo – 14 Days"],
    highlights: [
      "Shey Phoksundo Lake",
      "Tibetan culture & monasteries",
      "Remote Himalayan valleys",
      "Wildlife including blue sheep & snow leopards",
    ],
    image: "/destination/dolpa.jpg",
    routeImage: "/routes/dolpa.jpg",
    category: "Adventure",
  },
  {
    title: "Mohare Danda Trek",
    location: "Annapurna Region, Nepal",
    rating: 4.6,
    difficulty: "Easy to Moderate",
    days: 7,
    group: "4-12 people",
    altitude: "3,313m",
    seasons: "Sep-Nov, Mar-May",
    routes: [
      "Mohare Danda Trek – 7 Days",
      "Community Eco Trek – 6 Days",
      "Short Mohare Danda Trek – 5 Days",
    ],
    highlights: [
      "Stunning sunrise and sunset views from Mohare Danda",
      "Panoramic views of Annapurna and Dhaulagiri ranges",
      "Community-based eco-tourism experience",
      "Peaceful trails with fewer crowds",
    ],
    image: "/destination/moharedanda.jpg",
    routeImage: "/routes/mohareroute.png",
    category: "Eco-Trek",
  },

  {
    title: "Chitwan Jungle Safari",
    location: "Chitwan National Park, Nepal",
    rating: 4.7,
    difficulty: "Easy",
    days: 3,
    group: "2-10 people",
    altitude: "415m",
    seasons: "All year",
    routes: ["Chitwan Safari – 3 Days"],
    highlights: [
      "Jeep safari",
      "Rhino and tiger spotting",
      "Tharu culture",
      "Bird watching",
    ],
    image: "/destination/chitwan.jpg",
    routeImage: "/routes/chitwanroute.jpg",
    category: "Tour",
  },
  {
    title: "Humla Trek",
    location: "Humla, Far Western Nepal",
    rating: 4.7,
    difficulty: "Challenging",
    days: 18,
    group: "4-8 people",
    altitude: "5,200m",
    seasons: "Apr-May, Sep-Oct",
    routes: [
      "Humla High Pass Trek – 18 Days",
      "Hilsa to Simikot Trek – 12 Days",
    ],
    highlights: [
      "Remote high-altitude landscapes",
      "Traditional Tibetan & Himalayan villages",
      "Karnali River rafting optional",
      "Less crowded and adventurous",
    ],
    image: "/destination/humla.jpg",
    routeImage: "/routes/humla.jpg",
    category: "Adventure",
  },
  {
    title: "Karnali Region Trek",
    location: "Karnali, Western Nepal",
    rating: 4.6,
    difficulty: "Moderate to Challenging",
    days: 14,
    group: "4-10 people",
    altitude: "4,800m",
    seasons: "Mar-May, Sep-Nov",
    routes: ["Karnali Circuit – 14 Days", "Rara to Jumla Trek – 10 Days"],
    highlights: [
      "Rara Lake views",
      "Remote villages & culture",
      "Pristine forests and rivers",
      "Wildlife spotting and adventure",
    ],
    image: "/destination/karnali.jpg",
    category: "Trek",
  },

  {
    title: "Great Himalaya Trail",
    location: "Across Nepal",
    rating: 5.0,
    difficulty: "Challenging",
    days: 150,
    group: "2-8 people",
    altitude: "6,190m",
    seasons: "Mar-May, Sep-Nov",
    routes: [
      "Eastern GHT Section – 50 Days",
      "Western GHT Section – 40 Days",
      "Full GHT Traverse – 150 Days",
    ],
    highlights: [
      "Traverse entire Nepal Himalayas",
      "Everest, Annapurna & Kanchenjunga views",
      "Remote high passes & villages",
      "Ultimate trekking adventure",
    ],
    image: "/destination/GreatHimal.jpg",
    category: "Trek",
  },
  {
    title: "Limi Valley Trek",
    location: "Humla District, Far-Western Nepal",
    rating: 4.7,
    difficulty: "Challenging",
    days: 18,
    group: "4-10 people",
    altitude: "4,950m",
    seasons: "Jun-Sep, Apr-Oct",
    routes: [
      "Limi Valley Trek – 18 Days",
      "Humla Limi Valley Trek – 20 Days",
      "Simikot to Limi Valley Trek – 19 Days",
    ],
    highlights: [
      "Remote trans-Himalayan valley with Tibetan culture",
      "Stunning views of Mt. Kailash and Saipal Himal",
      "Ancient monasteries and meditation caves",
      "Untouched wilderness and authentic village life",
    ],
    image: "/destination/limivalley.jpeg",
    routeImage: "/routes/limiroute.webp",
    category: "Remote Trek",
  },

  {
    title: "Bhaktapur Tour",
    location: "Bhaktapur, Nepal",
    rating: 4.7,
    difficulty: "Easy",
    days: 1,
    group: "2-20 people",
    altitude: "1,400m",
    seasons: "All Year",
    routes: ["Bhaktapur Heritage Walk – 1 Day"],
    highlights: [
      "UNESCO World Heritage city",
      "Durbar Square & temples",
      "Newari art, culture & food",
      "Pottery Square & Nyatapola Temple",
    ],
    image: "/destination/bhaktapur.jpg",
    category: "Cultural Tour",
  },

  {
    title: "Patan Tour",
    location: "Lalitpur, Nepal",
    rating: 4.6,
    difficulty: "Easy",
    days: 1,
    group: "2-20 people",
    altitude: "1,350m",
    seasons: "All Year",
    routes: ["Patan Heritage Walk – 1 Day"],
    highlights: [
      "Patan Durbar Square (UNESCO site)",
      "Ancient Newari architecture",
      "Buddhist stupas & courtyards",
      "Local handicrafts & museum visit",
    ],
    image: "/destination/patan.jpg",
    category: "Cultural Tour",
  },
  {
    title: "Bardiya National Park Safari",
    location: "Bardiya, Western Nepal",
    rating: 4.5,
    difficulty: "Easy",
    days: 3,
    group: "2-10 people",
    altitude: "200m",
    seasons: "All year",
    routes: ["Bardiya Safari – 3 Days", "Dorptan Jungle Tour – 2 Days"],
    highlights: [
      "Jeep safari inside Bardiya National Park",
      "Rhino and tiger spotting",
      "Bird watching and flora exploration",
      "Cultural interaction with local Tharu community",
    ],
    image: "/destination/bardiya.jpg",
    category: "Tour",
  },
  {
    title: "Lumbini Tour",
    location: "Lumbini, Nepal",
    rating: 4.6,
    difficulty: "Easy",
    days: 2,
    group: "2-15 people",
    altitude: "200m",
    seasons: "All year",
    price: 399,
    oldPrice: 499,
    routes: ["Lumbini – 2 Days"],
    highlights: [
      "Birthplace of Lord Buddha",
      "Monastery visits",
      "Peaceful gardens",
    ],
    image: "/destination/lumbini.jpg",
    category: "Tour",
  },
  {
    title: "Kathmandu Valley Tour",
    location: "Kathmandu, Nepal",
    rating: 4.7,
    difficulty: "Easy",
    days: 3,
    group: "2-15 people",
    altitude: "1,400m",
    seasons: "All year",
    price: 599,
    oldPrice: 699,
    routes: ["Kathmandu Sightseeing – 3 Days"],
    highlights: [
      "Pashupatinath, Boudhanath, Durbar Square",
      "Local culture & cuisine",
      "Shopping at Thamel",
    ],
    image: "/destination/kathmandu.jpg",
    routeImage: "/routes/ktm.png",
    category: "Tour",
  },
  {
    title: "Pokhara & Surrounding Trek",
    location: "Pokhara, Nepal",
    rating: 4.8,
    difficulty: "Moderate",
    days: 5,
    group: "4-12 people",
    altitude: "820m",
    seasons: "Sep-Nov, Mar-May",
    price: 799,
    oldPrice: 899,
    routes: ["Pokhara Short Trek – 5 Days"],
    highlights: [
      "Fewa Lake views",
      "Sarangkot sunrise",
      "Caves and waterfalls",
      "Adventure activities",
    ],
    image: "/destination/pokhara.jpg",
    routeImage: "/routes/pokhara.png",
    category: "Trek",
  },
  {
    title: "Kanchenjunga Trek",
    location: "Taplejung, Nepal",
    rating: 4.9,
    difficulty: "Challenging",
    days: 20,
    group: "4-10 people",
    altitude: "8,586m",
    seasons: "Mar-May, Sep-Nov",
    price: 4599,
    oldPrice: 4699,
    routes: ["Kanchenjunga Base Camp – 20 Days"],
    highlights: [
      "Views of Mt. Kanchenjunga",
      "Remote trails and villages",
      "High-altitude adventure",
    ],
    image: "/destination/kanchanjunga.jpg",
    routeImage: "/routes/kanchanjunga.png",
    category: "Adventure",
  },
  {
    title: "Dhaulagiri Trek",
    location: "Dhaulagiri Region, Nepal",
    rating: 4.8,
    difficulty: "Challenging",
    days: 16,
    group: "4-10 people",
    altitude: "8,167m",
    seasons: "Oct-Dec, Mar-May",
    price: 4399,
    oldPrice: 4499,
    routes: ["Dhaulagiri Circuit – 16 Days"],
    highlights: [
      "Views of Mt. Dhaulagiri",
      "Remote valleys and glaciers",
      "Cultural villages en route",
    ],
    image: "/destination/dhaulagiri.jpg",
    routeImage: "/routes/dhaulagiri.jpg",
    category: "Adventure",
  },
  {
    title: "Damodar Kunda Trek",
    location: "Upper Mustang, Nepal",
    rating: 4.6,
    difficulty: "Moderate to Challenging",
    days: 12,
    group: "4-12 people",
    altitude: "4,890m",
    seasons: "May-Oct",
    routes: [
      "Damodar Kunda Trek – 12 Days",
      "Upper Mustang with Damodar Kunda – 15 Days",
      "Pilgrimage Damodar Kunda Trek – 10 Days",
    ],
    highlights: [
      "Sacred Himalayan lake revered by Hindus and Buddhists",
      "Breathtaking Upper Mustang landscapes",
      "Views of Annapurna, Dhaulagiri, and Nilgiri ranges",
      "Cultural exploration of Tibetan-influenced villages",
    ],
    image: "/destination/damodartrek.jpg",
    routeImage: "/routes/damodar.png",
    category: "Pilgrimage Trek",
  },
  {
    title: "Ruby Valley Trek",
    location: "Ganesh Himal Region, Nepal",
    rating: 4.6,
    difficulty: "Moderate",
    days: 10,
    group: "4-12 people",
    altitude: "3,850m",
    seasons: "Sep-Nov, Mar-May",
    routes: [
      "Ruby Valley Trek – 10 Days",
      "Ganesh Himal Ruby Valley Trek – 12 Days",
      "Short Ruby Valley Trek – 7 Days",
    ],
    highlights: [
      "Scenic views of Ganesh Himal, Langtang, and Manaslu ranges",
      "Authentic Tamang and Gurung culture",
      "Natural hot springs and waterfalls",
      "Off-the-beaten-path experience with fewer trekkers",
    ],
    image: "/destination/rubyvalley.jpeg",
    routeImage: "/routes/ruby_valley.jpg",
    category: "Community Trek",
  },

  {
    title: "Rara Trek",
    location: "Mugu, Nepal",
    rating: 4.7,
    difficulty: "Moderate",
    days: 8,
    group: "4-10 people",
    altitude: "2,990m",
    seasons: "Mar-May, Sep-Nov",
    price: 1199,
    oldPrice: 1299,
    routes: ["Rara Lake Trek – 8 Days"],
    highlights: [
      "Pristine Rara Lake",
      "Remote and peaceful trekking",
      "Local culture and wildlife",
    ],
    image: "/destination/rara.jpg",
    routeImage: "/routes/rara.jpg",
    category: "Trek",
  },
  {
    title: "Ama Yangri Trek",
    location: "Helambu Region, Nepal",
    rating: 4.5,
    difficulty: "Easy to Moderate",
    days: 5,
    group: "4-10 people",
    altitude: "3,771m",
    seasons: "Sep-Nov, Mar-May",
    routes: [
      "Ama Yangri Trek – 5 Days",
      "Helambu Ama Yangri Trek – 6 Days",
      "Short Ama Yangri Hike – 3 Days",
    ],
    highlights: [
      "360° panoramic views including Langtang, Everest, and Jugal ranges",
      "Sacred Ama Yangri peak with Buddhist significance",
      "Scenic trails through rhododendron and pine forests",
      "Cultural encounters with Tamang and Sherpa villages",
    ],
    image: "/destination/ama.jpg",
    routeImage: "/routes/amaroute.png",
    category: "Trek",
  },



];
